namespace Bouncer.Core
{
    public enum SoundCue
    {
        Throw,
        ThrowCharged,
        ThrowCandle,
        Catch,
        CatchCandle,
        CatchMiss,
        Pickup,
        Dash,
        PlayerHurt,
        PlayerKnockedOut,
        BallWall,
        AreaThud,
        SwingBat,

        EnemyHit,
        EnemyHitStrong,
        RolyPolyChime,
        RolyPolyPop,
        PupsikSqueak,
        PupsikPop,
        SoldierThrow,
        SoldierPop,
        BossSplit,
        SpawnWarning,

        LevelUp,
        CardPick,
        UiMove,
        Victory,
        GameOver,

        Coin,
        Portfolio,
        KioskOpen,
        Purchase,
        NotEnoughCoins,
        EliteSpawn,
        Explosion,
        ShieldBlock,
        BallStuck,

        Whistle,
        Thunder,
        MannequinPose,
        ShadowHiss,
        ScarecrowCatch,
        LampOut,
        SecondWind,

        BabaiLaugh,
        CountTick,
        FoundYou,
        PoleLand,
        CarouselSpin,
        CrowCaw,
        CrowFlap,
        DecoyBurst,
        SackStuff,
        SackSpill,
        DarkWave,
        MomCall,
        DoorOpen,

        Siren,
        TransformClank,
        PlushThump,
        SeamRip,
        DollCry,
        DrumBeat,
        WindUp,
        ZapperShot,
        EngineRev,

        FenceRise,
        FenceKnock,
        BubbleBlow,
        BubblePop,
        CapGun,
        CameraFlash,
        MagnetPull,
        Rewind,
        ElasticTwang,
        RadioCrackle,
        TamagotchiBeep,
        ChalkScribble,
        SpinWhoosh,
        AbilityNotReady,
    }
}
